// Generated by CoffeeScript 1.4.0
'use strict';

/* A service that manages a common view of the graph for the entire app
*/

angular.module('app.services.jmx', []).factory('jmxService', [
  '$http', '$rootScope', function($http, $rootScope) {
    var JmxService;
    JmxService = (function() {

      function JmxService() {}

      return JmxService;

    })();
    return new JmxService;
  }
]);
